### ISSUE TITLE
Cluster views change their location constantly when zooming (even very slightly) on low zoom

### ISSUE THREAD

**Issue by IVANKRUPSKI** [efremidze/Cluster#60] opened 2017-11-23 14:18 UTC
### Issue Description
(1) Cluster views change their location constantly when zooming (even very slightly) on low zoom, (2) they move far from the actual pins locations, 
(3) occasionally on very low zoom pins pop up.

All this somehow linked to this method `manager.shouldCenterAlignClusters = true`

### Screenshots
![screenshot at nov 23 15-23-57](https://user-images.githubusercontent.com/16180201/33177296-624e7f72-d062-11e7-95e6-9e9089f2490c.png)

### Environment

- **iOS Version**: IOS 11, IOS 10
- **Device(s)**: iPhone 6s+, iPhone 5

**Comment by efremidze** [comment] 2017-11-23 21:26
Does it work properly when `manager.shouldCenterAlignClusters = false`?

**Comment by IVANKRUPSKI** [comment] 2017-11-23 21:40
Yea, it seems to work without this strange behavior when it’s false.

But in this case the bug with overlapping cluster views and pins appears.

**Comment by jose46moreno** [comment] 2017-11-24 18:53
It happens to me too. It put the group on top of the sea when in reality there is no one there.
Any help?

**Comment by efremidze** [comment] 2017-11-24 19:46
The pins shouldn't be centered, only the clusters. Ill take a look. The clusters landing in the sea are normal since it is placing them in the center of quadrants.

**Comment by jose46moreno** [comment] 2017-11-24 20:07
You could modify it so that the clusters are created, not in the center, if not in reference to the last or first of the pins with a bit of deviation, if you want.

I think it would be a good idea.

I have three pins in Spain, and when zooming out, as are the 3 near the coast, place the cluster in the sea.

**Comment by efremidze** [comment] 2017-11-24 20:16
In your case I would set `manager.shouldCenterAlignClusters = true` since it does that exactly.

**Comment by jose46moreno** [comment] 2017-11-26 19:26
With manager.shouldCenterAlignClusters = true, the pins , when zooming out, as are the 3 near the coast, place the cluster in the sea.

Could you tell me how to modify your excellent library so that the tool set is placed in the coordinates of the last or first pin?

**Comment by efremidze** [comment] 2017-11-27 18:26
I meant `manager.shouldCenterAlignClusters = false` should do that?

**Comment by jose46moreno** [comment] 2017-11-28 19:16
I have a bigger problem

When the change is the location, often do not see the pines if I do not zoom and zoom out, and sometimes even doing so not all are displayed.

Could you help me, please, to solve this?

It is very important for my project.

**Comment by efremidze** [comment] 2017-11-28 20:32
Im adding options for displaying clusters, however ur issue is probably unrelated. Please post an example so I can reproduce it.

**Comment by efremidze** [comment] 2017-11-29 02:09
Im fixing the bug now

**Comment by efremidze** [comment] 2017-12-01 06:50
Fixed in [2.0.3](https://github.com/efremidze/Cluster/releases/tag/2.0.3)

**Comment by dneykov** [comment] 2017-12-06 09:08
I have similar problem with 2.1.0
I have clusters in 2 continents and when I zoom out to see both clusters cluster counts are changing when when changing zoom levels.

**Comment by efremidze** [comment] 2017-12-06 09:12
Thats normal since the grid keeps changing.

**Comment by dneykov** [comment] 2017-12-06 09:16
I don't think is normal because I have cluster with about 3k annotations in Africa and 6k in Europe. When I'm slightly changing zoom level these numbers swaps. So it shows 3k in Europe and 6k in Africa which is totally wrong.

**Comment by jose46moreno** [comment] 2017-12-06 09:32
Now it works worse.

When I change the location of the map, it does not show me the annotations or the clusters.

When I charge it for the first time either.

I have to be zooming so that they start to see each other.

You could review it?

**Comment by efremidze** [comment] 2017-12-06 18:55
@jose46moreno which version?

**Comment by efremidze** [comment] 2017-12-06 21:25
Im testing it and everything appears right. Ill add unit tests. Help is appreciated.

**Comment by dneykov** [comment] 2017-12-07 08:23
@efremidze Yes this is the case in 2.1.0 as well
Here are examples on different zoom levels with 2.1.0

![screen shot 2017-12-07 at 9 48 02 am copy](https://user-images.githubusercontent.com/5511034/33705328-8b04cee0-db38-11e7-8a6e-dae61a252300.png)
![screen shot 2017-12-07 at 9 52 10 am copy](https://user-images.githubusercontent.com/5511034/33705329-8b242a1a-db38-11e7-9f51-2e0940297aec.png)
![screen shot 2017-12-07 at 9 52 27 am copy](https://user-images.githubusercontent.com/5511034/33705330-8b420968-db38-11e7-868d-29c515aa160e.png)

**Comment by efremidze** [comment] 2017-12-07 09:09
What `clusterPosition` are you using?

**Comment by dneykov** [comment] 2017-12-07 09:15
`manager.clusterPosition = .nearCenter`

**Comment by efremidze** [comment] 2017-12-07 18:46
are u having the same issue when setting it to `manager.clusterPosition = .average`?

**Comment by dneykov** [comment] 2017-12-07 19:06
@efremidze I have tried `. center` before but the result is the same. I didn't tried `. average ` but can try it at Monday and will let you know the result.

**Comment by jose46moreno** [comment] 2017-12-07 19:49
@efremidze the version is 2.1.0.

Besides the problem that clusters do not appear at times, it also happens to me as a @dneykov and that is that it moves position clusters when I zoom.

**Comment by tdimeco** [comment] 2017-12-08 09:26
Actually this is an old issue, see #15.

**Comment by dneykov** [comment] 2017-12-08 09:37
In #15 the problem is solved with version 1.0.7 as I mentioned above version 1.0.7 works as expected but the versions after that have same problem.

**Comment by jose46moreno** [comment] 2017-12-08 18:42
Help?

**Comment by efremidze** [comment] 2017-12-08 21:55
Its not related to #15, that issue related to a meridian bug.

**Comment by efremidze** [comment] 2017-12-08 21:57
Can u guys send me a sample project to reproduce?

**Comment by jose46moreno** [comment] 2017-12-09 09:22
@efremidze here I leave a link to my Dropbox folder with the video where you can see the error:

https://www.dropbox.com/sh/exo23lipw6n0hs6/AACALNR29SY7v881CYZjcGRka?dl=0

And an image where I print the number of annotations by console:

<img width="439" alt="captura de pantalla 2017-12-09 a las 10 19 20" src="https://user-images.githubusercontent.com/8105593/33794343-c7bfdad0-dcca-11e7-9a79-f7c53290fb14.png">

Result:

<img width="99" alt="captura de pantalla 2017-12-09 a las 10 18 39" src="https://user-images.githubusercontent.com/8105593/33794344-cdebc108-dcca-11e7-9725-5a197663fe37.png">

**Comment by jose46moreno** [comment] 2017-12-09 10:26
Here you can see the entire function that runs in the viewWillAppear.

<img width="749" alt="captura de pantalla 2017-12-09 a las 11 21 30" src="https://user-images.githubusercontent.com/8105593/33794822-d18592ae-dcd3-11e7-86ef-fccfbe83181f.png">

The problem is that when you add the annotations to the manager, it does not call the method ViewFor of MapKit (I have put a print on that method and it does not run)

**Comment by jose46moreno** [comment] 2017-12-09 10:44
@efremidze here another video, with your own example, where every time I change and return to sight, the pins move position.

I also attach the project.

https://www.dropbox.com/sh/exo23lipw6n0hs6/AACALNR29SY7v881CYZjcGRka?dl=0

**Comment by efremidze** [comment] 2017-12-11 06:35
`mapView.centerCoordinate` doesn't call `regionDidChangeAnimated` or `reload:`

**Comment by dneykov** [comment] 2017-12-13 14:18
I completely rewrote my mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) delegate method and now everything seems to work as expected with manager.clusterPosition = . average and Cluster version 2.1.0

**Comment by IVANKRUPSKI** [comment] 2017-12-14 23:35
Great!
manager.clusterPosition = .average does the work.

However there again appeared the problem that was described in #49. 
Any chances it could be solved?

**Comment by efremidze** [comment] 2017-12-15 02:45
Increasing the cell size fixes that issue, however it needs to be done dynamically. I need to investigate a good solution for that.

**Comment by jose46moreno** [comment] 2017-12-16 10:06
@dneykov could you share your rewrote viewFor delegate?

I am not able to make it work.

When I change the view and return, the annotations disappear or only some of them appear.

**Comment by jose46moreno** [comment] 2017-12-16 20:45
@efremidze You think you could implement some animation for the grouping and ungrouping of the annotations.

Something like they all come together at one point and separate.

It would be incredible and improve the user experience.

**Comment by IVANKRUPSKI** [comment] 2017-12-17 01:29
Sorry didn't get it. What is meant by the cell size?
This ->   manager.maxZoomLevel = 20 ?

**Comment by efremidze** [comment] 2017-12-17 23:13
@jose46moreno I'll create a separate issue for that

@IVANKRUPSKI `manager.cellSize = 20`

**Comment by IVANKRUPSKI** [comment] 2017-12-17 23:20
Got it, thanks!

**Closed** 2018-04-17 05:42 UTC
Labels: bug
